### ISSUE TITLE
Project Initiation: List the requirements, platform (implementation method), and development environment.

### ISSUE THREAD

**Issue by wsqstar** [AierLab/MultiverseNote#1]
项目立项 列出需求，使用平台（实现方式），开发环境

请在评论中列出：
- 使用需求
- 使用平台（实现方式：插件，独立软件，类git）
- 开发环境
- 其他

Please list in the comments:
- Your equirements
- Platform used (implementation method：pulg-in, independent software, git-like tools)
- Development environment
- other info you might want to provide

**Comment by yhbcode000** [comment]
## 使用需求
- 用户能够在主分支讨论主题，并在遇到问题时创建新的分支进行深入探讨。
- 支持直观的界面展示所有分支。
- 允许通过拖拽操作进行分支管理。

## 使用平台
- **实现方式**：作为插件和独立软件，支持类git操作。

## 开发环境
- **前端**：JavaScript
- **后端**：Python
- **操作系统**：Windows, macOS, Linux

---

## Your Requirements
- Users should be able to discuss topics on the main branch and create new branches for in-depth discussions when encountering issues.
- Support an intuitive interface to display all branches.
- Allow branch management through drag-and-drop operations.

## Platform Used
- **Implementation Method**: As a plugin and standalone software, supporting git-like operations.

## Development Environment
- **Frontend**: JavaScript
- **Backend**: Python
- **Operating Systems**: Windows, macOS, Linux
