### ISSUE TITLE
Database handler and json storage template specify

### ISSUE THREAD

**Issue by yhbcode000** [AierLab/MultiverseNote#13]
Issue Statement:

The project requires implementing a JSON-based system for storing conversation history, referencing the ChuanHuChatGPT model. This involves creating a template JSON file for restoration documentation, as well as developing Python handlers on both the backend and potentially the frontend to manage and display the data.

List of TODOs:
1. Reference ChuanHuChatGPT to create a template JSON file handler for restoration documentation.
2. Develop Python handlers in the backend to read and process the JSON file.
3. Consider developing handlers for the frontend to display the JSON data.

Subject to Discussion:
Should the frontend directly read the local JSON file, or should it send a request to the server which then reads the JSON data and responds to the frontend request? Please leave your comments below to discuss the best approach.

**Comment by wsqstar** [comment]
both， local for privacy but server will bring better performance

**Comment by yhbcode000** [comment]
@wsqstar 
> both， local for privacy but server will bring better performance

Yes, local means privacy, but that is not the issue I want to discuss here. Having the frontend and backend access the same file is a common implementation for desktop apps using frameworks like Electron.js, which can reduce development complexity in terms of integration testing. If we implement it as a typical web development setup, we would need to create a data handler at the API level. This approach, while more standard, offers better scalability. So, I guess the issue I raised is somewhat unnecessary. To be honest, I favor the latter choice since there are more reference materials available, and it would be much easier to collaborate with others.

**Comment by Yubo-Shao** [comment]
Local history seems simpler to implement and we don't need to over complicate things. The encryption needed for the JSON strings in the data handler if we were to implement the server storage approach requires certainly more effort while not offering better security
