### ISSUE TITLE
Design the User Interface

### ISSUE THREAD

**Issue by yhbcode000** [AierLab/MultiverseNote#3]
Design the graphical user interface for the application, focusing on usability and intuitive navigation of branch management features.

**Comment by yhbcode000** [comment]
For the MVP, command line tools would suffice. Alternatively, use other interfaces and check the @branch_label for appending other discussion branches into the main stream.

**Comment by wsqstar** [comment]
update： we try to use chuanhu as a test platform for backend, but we still need to design an UI.

**Comment by yhbcode000** [comment]
Use taipy for a deployable web ui for real deployment of the application.
